function songRecommend = mood2songTitle(mood, musicClipNote, songNumber)
% Blue=1, Classical=2, Country=3, Disco=4, Hip-hop=5
% Jazz=6, Metal=7, POP=8, Reggae=9, Rock=10

if nargin <3, songNumber =1;end
musicType = unique(musicClipNote(1,:));


typeNumber = 2;

switch mood(1:3)
    case 'afr' % metal/rock
        typeChoose = [7,10];
    case 'ang' % metal/rock
        typeChoose = [7,10];
    case 'dis' % hiphop/metal
        typeChoose = [5,7];
    case 'hap' %pop/disco
        typeChoose = [8,4];
    case 'neu' %classical/reggae
        typeChoose = [2,9];
    case 'sad' % rock/country
        typeChoose = [10,3];
    case 'sur' %jazz/blue
        typeChoose = [6,1];
end

%%
% typeNumber = 2; typeChoose = [1,3]; songNumber = 2;
% musicType = unique(musicClipNote(1,:));

cnt = 1; 
for idxType =1:typeNumber
    musicLabelName = cell2mat(musicType(typeChoose(idxType)));
    song_bank = musicClipNote(2, typeChoose(idxType)); song_bank = song_bank{1};
    if songNumber > length(song_bank), songNumber = length(song_bank); end
    idxRandom = randperm(length(song_bank), songNumber);
    for idxSongNumber = 1:songNumber
        song.type = musicLabelName;
        song.idx = cell2mat(song_bank(idxRandom(idxSongNumber), 1));
        song.name = cell2mat(song_bank(idxRandom(idxSongNumber), 2));
        songRecommend{cnt} = song; 
        cnt = cnt+1;
        clear song;    
    end
end

%%
% songType = musicType(typeChoose);
% songIdx = zeros(songNumber,1);
% for type=1:length(typeChoose)
%     for num=1:songNumber
%         idx = round(rand(1)*10);
%         song_bank = musicClipNote(2, typeChoose(type));
%          songIdx(num) = song_bank(idx,:);
% %         songTitle{num} = musicClipNote(
%     end
% end













% function [songIdx, label] = mood2songTitle(mood)
% 
% % song bank
% music_label = {'blue' 'classical' 'country' 'disco' 'hiphop' 'jazz' 'metal' 'pop' 'reggae' 'rock'};
% song_bank = struct(music_label{1},{{'One Bourbon One Scotch One Beer',...
%                                     'John Lee Hooker - Think Twice Before',...
%                                      'John Lee Hooker - Im Bad Like Jesse James',...
%                                      'John Lee Hooker - Walkin The Boogie',...
%                                      'Hellhound on my trail by Robert Johnson',...
%                                      'Stevie Ray Vaughan & Double Trouble - Rude Mood',...
%                                      'Magic Slim - Pleas Dont Dog Me',...
%                                      'The Man You Need - Magic Slim',...
%                                      'Clifton Chenier - All Night Long',...
%                                      'Clifton Chenier - Think It Over'}},...                                     
%                   music_label{2},{{'Bach - Oboe dAmore Concerto in D BWV 1053',...
%                                     'Concerto in B-Flat, Wq. 164: II. Largo E Mesto',...
%                                      'symphony no. 39 in e-flat k. 543',...
%                                      'symphony no.41 in c k 551 jupiter',...
%                                      'Ainsi la nuit, for string quartet',...
%                                      'violin concerto no 1 op 35',...
%                                      'west side story symphonic dances',...
%                                      'Piano Sonata No.21 in B',...
%                                      'Haydn: Symphony in F minor, HI No.49',...
%                                      'Hill Song No.2'}},...
%                  music_label{3},{{'Faith Hill - Just To Hear You Say That You Love Me',...
%                                     'If Tomorrow Never Comes',...
%                                      'Outbound Plane',...
%                                      'John Anderson - Straight Tequila Night',...
%                                      'I Cant Stop Loving You',...
%                                      'A Church A Courtroom and Then Goodbye Patsy Cline',...
%                                      'Im Gonna Be a Country Girl Again',...
%                                      'Tell Laura I Love Her',...
%                                      'Today I Started Loving You Again',...
%                                      'Tryin To Get Over You'}},...
%                 music_label{4},{{'I Will Survive',...
%                                     'Carl Douglas - Run Back',...
%                                      'Native New Yorker - Odyssey',...
%                                      'Miquel Brown - So Many Men, So Little Time',...
%                                      'I am What I am',...
%                                      'Always and Forever',...
%                                      'Chic - I Want Your Love',...
%                                      'Earth, Wind and Fire - Fantasy',...
%                                      'Anita Ward - Ring My Bell',...
%                                      'Peter Brown DANCE WITH ME'}},...
%                music_label{5},{{'looking for the perfect beat',...
%                                     'Beastie Boys : Skills to Pay the Bills',...
%                                      'Beastie Boys - The Negotiation Limerick File',...
%                                      'De La Soul - Buddy (Native Tongue Decision)',...
%                                      'Lauryn Hill - Ex-Factor',...
%                                      'A Tribe Called Quest - Electric Relaxation',...
%                                      'cypress hill - What Go Around Come Around',...
%                                      'Buggin Out by A Tribe Called Quest',...
%                                      'Public Enemy-Contract On The World Love Jam',...
%                                      'Public Enemy Who Stole the Soul'}},...
%                music_label{6},{{'on the town three dance episodes',...
%                                     'Lonnies lament joe lovano',...
%                                      'I cant get started joe lovano',...
%                                      'dewey baby branford Marsalis',...
%                                      'she funny that way coleman hawkins',...
%                                      'body and soul coleman Hawkins',...
%                                      'Henry "Red" Allen - Ive Got the World on a String',...
%                                      'Henry “Red?Allen ?World On A String',...
%                                      'life of the party tony Williams',...
%                                      'all blues miles davis'}},...
%                music_label{7},{{'iron maiden wasted years',...
%                                     'my faeryland forgotten',...
%                                      'necrophobic slayer',...
%                                      'trust megadeth',...
%                                      'stand up and shout dio',...
%                                      'jukebox lean',...
%                                      'Welcome To The Jungle',...
%                                      'Bon Jovi - U give love a bad name',...
%                                      'XXXXX',...
%                                      'XXXXX'}},...
%                music_label{8},{{'Hand In My Pocket',...
%                                     'Head Over Feet',...
%                                      'Its Like Rain on Your Wedding Day',...
%                                      'Every Breath You Take',...
%                                      'Britney Spears (You Drive Me) Crazy',...
%                                      'Britney Spears Satisfaction',...
%                                      'Autumn Goodbye',...
%                                      'What A Girl Wants',...
%                                      'Bootylicious',...
%                                      'Abigail - If It Dont Fit'}},...
%                music_label{9},{{'Is This Love',...
%                                     'no woman no cry',...
%                                      'Every little thing gonna be all right',...
%                                      'Buffalo Soldier',...
%                                      'Trenchtown Rock',...
%                                      'Sitting and watching',...
%                                      'Some Like It Hot',...
%                                      'Freddie McGregor - Prophecy',...
%                                      'Here Comes The Hotstepper',...
%                                      'Many Rivers To Cross'}},...
%               music_label{10},{{'Morphine..... Potion',...
%                                     'Ani Di Franco - Worthy',...
%                                      'Ani Di Franco - Cradle and all',...
%                                      'Ani DiFranco - Shy',...
%                                      'Another One Bites The Dust',...
%                                      'Hello Mary Lou',...
%                                      'Bohemian Rhapsody',...
%                                      'Big spender',...
%                                      'Let The Children Speak',...
%                                      'Sting Russians'}});
% 
% %mood to music label mapping
% %mood = 'afraid'
% 
% songIdx = round(rand(1)*10);
% switch mood(1:3)
%     case 'afr'
% %         display('afraid')
%         song_tmp = song_bank.metal;
%         song_title1 = song_tmp{songIdx};
%         song_tmp = song_bank.rock;
%         song_title2 = song_tmp{songIdx};
%     case 'ang'
% %         display('angry')
%         song_tmp = song_bank.metal;
%         song_title1 = song_tmp{songIdx};
%         song_tmp = song_bank.rock;
%         song_title2 = song_tmp{songIdx};
%     case 'dis'
% %         display('disgust')
%         song_tmp = song_bank.metal;
%         song_title1 = song_tmp{songIdx};
%         song_tmp = song_bank.hiphop;
%         song_title2 = song_tmp{songIdx};
%     case 'hap'
% %         display('happy')  
%         song_tmp = song_bank.pop;
%         song_title1 = song_tmp{round(rand(1)*10)};
%         song_tmp = song_bank.disco;
%         song_title2 = song_tmp{round(rand(1)*10)};
%     case 'neu'
% %         display('neutral')
%         song_tmp = song_bank.classical;
%         song_title1 = song_tmp{round(rand(1)*10)};
%         song_tmp = song_bank.reggae;
%         song_title2 = song_tmp{round(rand(1)*10)};
%     case 'sad'
% %         display('sad')
%         song_tmp = song_bank.rock;
%         song_title1 = song_tmp{round(rand(1)*10)};
%         song_tmp = song_bank.country;
%         song_title2 = song_tmp{round(rand(1)*10)};
%     case 'sur'
% %         display('surprise') 
%         song_tmp = song_bank.jazz;
%         song_title1 = song_tmp{round(rand(1)*10)};
%         song_tmp = song_bank.blue;
%         song_title2 = song_tmp{round(rand(1)*10)};
%         
% end
% label = {song_title1 song_title2};
% % round(rand(1)*10)
% 
